variable "registry_id" {
  description = "ID for the container registry"
  type        = string
}

variable "context" {
  description = "Context_path for the container registry docker task"
  type        = string
}

variable "image_names" {
  description = "Image names to be generated by the container registry docker task"
  type        = list(string)
}

variable "context_token" {
  description = "value of the context token"
  type        = string
}
